name: appcliente
description: "Aplicacion oficial de Followcar."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aquí agregamos la sección de assets
  assets:

     - assets/verify3.png
     - assets/imageservicios.png
     - assets/imagetaller.png
     - assets/perfil.png
     - assets/logohome.png

     - assets/verify3.webp
     - assets/imageservicios.webp
     - assets/imagetaller.webp
     - assets/perfil.webp
     - assets/logohome.webp
     
      # Ruta de la imagen que quieres usar

