name: appcliente
description: "Aplicacion oficial de Followcar."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aquí agregamos la sección de assets
  assets:

     - assets/verify3.webp
     - assets/imageservicios.webp
     - assets/imagetaller.webp
     - assets/perfil2.webp
     - assets/logoapphome.webp
     - assets/SplashMeca.webp
     - assets/ImageDelTaller.webp
     - assets/ZKZg.gif

 

